<?php 
echo "<chart>\n";
echo "  <license>GT7WS733UFV9OZCI3PQUDSQT34CJOL</license>\n";
echo "	<chart_data>\n";
echo "		<row>\n";
echo "			<null/>\n";
echo "			<string>test,test</string>\n";
echo "			<string>Douglas, Blair</string>\n";
echo "			<string>Felleman, Cassandr</string>\n";
echo "			<string>Ferreira, Tiana</string>\n";
echo "			<string>Hasan, Rashad</string>\n";
echo "			<string>Owens, Aaron</string>\n";
echo "			<string>Sparks, Rebecca</string>\n";
echo "			<string>Wubishet, Elizabet</string>\n";
echo "		</row>\n";
echo "		<row>\n";
echo "			<string>Aux Time</string>\n";
echo "			<number shadow='data' bevel='data'>" . rand(1,10) . "</number>\n";
echo "			<number shadow='data' bevel='data'>" . rand(1,10) . "</number>\n";
echo "			<number shadow='data' bevel='data'>" . rand(1,10) . "</number>\n";
echo "			<number shadow='data' bevel='data'>" . rand(1,10) . "</number>\n";
echo "			<number shadow='data' bevel='data'>" . rand(1,10) . "</number>\n";
echo "			<number shadow='data' bevel='data'>" . rand(1,10) . "</number>\n";
echo "			<number shadow='data' bevel='data'>" . rand(1,10) . "</number>\n";
echo "			<number shadow='data' bevel='data'>" . rand(1,10) . "</number>\n";
echo "		</row>\n";
echo "		<row>\n";
echo "			<string>Talk Time</string>\n";
echo "			<number shadow='data' bevel='data'>" . rand(1,20) . "</number>\n";
echo "			<number shadow='data' bevel='data'>" . rand(1,20) . "</number>\n";
echo "			<number shadow='data' bevel='data'>" . rand(1,20) . "</number>\n";
echo "			<number shadow='data' bevel='data'>" . rand(1,20) . "</number>\n";
echo "			<number shadow='data' bevel='data'>" . rand(1,20) . "</number>\n";
echo "			<number shadow='data' bevel='data'>" . rand(1,20) . "</number>\n";
echo "			<number shadow='data' bevel='data'>" . rand(1,20) . "</number>\n";
echo "			<number shadow='data' bevel='data'>" . rand(1,20) . "</number>\n";
echo "		</row>\n";
echo "		<row>\n";
echo "			<string>Available</string>\n";
echo "			<number shadow='data' bevel='data'>" . rand(1,20) . "</number>\n";
echo "			<number shadow='data' bevel='data'>" . rand(1,20) . "</number>\n";
echo "			<number shadow='data' bevel='data'>" . rand(1,20) . "</number>\n";
echo "			<number shadow='data' bevel='data'>" . rand(1,20) . "</number>\n";
echo "			<number shadow='data' bevel='data'>" . rand(1,20) . "</number>\n";
echo "			<number shadow='data' bevel='data'>" . rand(1,20) . "</number>\n";
echo "			<number shadow='data' bevel='data'>" . rand(1,20) . "</number>\n";
echo "			<number shadow='data' bevel='data'>" . rand(1,20) . "</number>\n";
echo "		</row>\n";
echo "	</chart_data>\n";
echo "	<update url='http://www.voast.com/maani/chart_data.php' delay='4' mode='normal' />\n";
echo "</chart>\n";
?>